### ISSUE TITLE
Question: how to deal with server side validation exceptions

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-form-native#10]
How do I deal w server side validation in case some kind of validation exception occurs that's not caught by client side validation. E.g. an email has to be unique and isn't, a wrong password is entered, etc?

**Comment by gcanti** [comment]
relevant tcomb-form issue (APIs are similar):

https://github.com/gcanti/tcomb-form/issues/79

**Comment by mschipperheyn** [comment]
Related to this is how to show a related server side validation message?

**Comment by gcanti** [comment]
Yes, the gist is that you can set the `options` on the fly, based on server validation:

```js
this.setState({
  options: {
    fields: {
      email: {
        hasError: true, // <- tell tcomb-form-native to show the error message
        error: 'Invalid email' // <- server error message text
      }
    }
  }
});
```

**Comment by mschipperheyn** [comment]
Ok, sounds like my comments on tcomb-validation are invalidated by this.

**Comment by mschipperheyn** [comment]
I see a few issues with this approach because we seem to be basically replacing the default exception object:
* Any server side exception overwrites the default exception. So, you have to save and reset the error message after replacing it with a server side message
* Same goes for hasError. You have to reset this value when the user submits the form again
* You have to mix in the exception with the original object, otherwise you will lose stuff such a label fields.

All in all, it would be nice to be able to have some method to handle this for you

**Comment by gcanti** [comment]
> I see a few issues with this approach

I agree but keep in mind that tcomb-form(-native) is a **low level library**. The nice side effect is that many use cases can be handled very concisely (due to tcomb's syntax and some sensible default).

What you have to do with the `option` object is similar to what you do using react's `setState` (overwrites the previous values).
You could use helper methods (like tcomb's immutability helpers https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#rendering-options)

> All in all, it would be nice to be able to have some method to handle this for you

Sure, I'm open to suggestions!
