### ISSUE TITLE
tcomb-validation dependency out of date

### ISSUE THREAD

**Issue by frankrowe** [gcanti/tcomb-form-native#146]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.2
- react-native v0.23.1
- tcomb-json-schema v0.3.0

### Expected behaviour

Form validates correctly when passed a json schema.

### Actual behaviour

tcomb-json-schema requires tcomb 3.0, while tcomb-validation requires tcomb 2.7.

This causes various bugs with validation, and can be fixed by bumping the tcomb-validation dependency to 3.0.

```shell
npm list tcomb
├── tcomb@3.0.0 
└─┬ tcomb-form-native@0.4.2
  └─┬ tcomb-validation@2.3.0
    └── tcomb@2.7.0 
```

**Comment by gcanti** [comment]
Hi @frankrowe,

> can be fixed by bumping the tcomb-validation dependency to 3.0

alternatively tcomb-json-schema v0.2.5 is compatible with the actual version of tcomb-form-native (v0.4.2).

(since upgrading to tcomb-validation v3 is technically a breaking change, I plan to postpone it in the next release of tcomb-form-native which already contains breaking changes)

**Comment by frankrowe** [comment]
Using tcomb-json-schema v0.2.5 works, thanks!
