### ISSUE TITLE
[Request] Use modals for datepicker

### ISSUE THREAD

**Issue by braco** [gcanti/tcomb-form-native#153]
https://github.com/eyaleizenberg/react-native-custom-action-sheet

![Image of Action Sheet](https://camo.githubusercontent.com/ad16108cec54b01e3bdd8b75850dd42963b93eb6/687474703a2f2f692e696d6775722e636f6d2f497136595a476a2e676966)

Inline display could default to using a textbox with the same styling. This behavior is more standard across both Android and iOS. I'm implementing this soon, will share when done.

**Comment by alvaromb** [comment]
This is doable right now with `tcomb-form-native`. I'm not sure if we have to support this out of the box instead of the actual, more flexible behaviour. /cc @gcanti

**Comment by gcanti** [comment]
The default template is just... a default, i.e. a bare working thing: `tcomb-form-native` might have published *without* a default, but then it would be difficult to show its features. 

My take on this is that every *advanced* customization should be done by writing your own template instead of enrich the default one.

**Comment by alvaromb** [comment]
Yeah, completely agree. @braco do you need help with building this custom behaviour?

**Comment by braco** [comment]
What about a secondary theme with common UX idioms? I can't think of any apps that inline large form elements like DatePicker.

@alvaromb: thanks for asking. Is there any reasonable way to get state in the templates without modifying the core package? Some of these will need to manage things like overlays.

**Comment by alvaromb** [comment]
Your template can access `locals`. This is a more complex example: https://github.com/APSL/react-native-floating-label/blob/master/FloatingLabel.js

**Comment by alvaromb** [comment]
Closing this by now. @braco, please read @gcanti's take on `tcomb-form-native` ecosystem about custom factories and templates https://github.com/gcanti/tcomb-form-native/issues/89

Basically, `tcomb-form-native` is the core platform to build good quality & validated forms, the UX/styles is handled entirely to its users, so your idea fits perfectly with a custom collection of templates (i.e., a Github repo with a collection of good quality templates for this lib).

Internally, we're working on this on our company, but it's moving at a slow pace due to the amount of work we have right now. Please ping me if you would like to be notified when the project moves forward.

**Comment by braco** [comment]
@alvaromb: thank you for the explanations, you've been very helpful. "factory" was the option I was missing. A little confused why Classes can't be used as global overrides:

```
Form.templates.thing = Class;
```

currently results in "Cannot call a class as a function". Why not inspect the template for function or Class type and behave accordingly? I would like to override all datepickers, as per the original example.
