### ISSUE TITLE
Tcomb form native handles keyboard behavior?

### ISSUE THREAD

**Issue by franzejr** [gcanti/tcomb-form-native#176]
I would like to know if this library handles this case: 

https://github.com/APSL/react-native-keyboard-aware-scroll-view

I'm facing this problem using the library. 

Thanks in advance,

**Comment by alvaromb** [comment]
@gcanti I receive tons of emails from Github issues, please assign me whenever you feel it's necessary, because sometimes the issues get buried 👍 

Hello @franzejr!

I'm the author of that library. If you wrap any `Form` with `TextInput`s inside, the `KeyboardAwareScrollView` component will auto resize and auto focus on the selected input. There is a small issue though: https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/25

You can workaround with the proposed PR to React Native and with the specified branch in the issue. If you need further help please open an issue in the other project, thanks!

**Comment by jsina** [comment]
@alvaromb I've got confused to how handle `KeyboardAwareScrollView` on Android. please help me about my problem. here is one of my component that I need to use `KeyboardAwareScrollView' but after many efforts I couldn't find the answer.

```
 <ScrollView>
        <View style={styles.container}>
          <View style={styles.header}>
            <View style={styles.colorPicker}>
              {colorButtons}
            </View>
            <Avatar
              borderColor="#fff"
              canEdit={true}
              style={{ backgroundColor: 'transparent' }}
              avatar={user.avatar}
              defaultPicture={defaultAvatar}
            />
          </View>
          <KeyboardAwareScrollView    >
            <Form
              refHandler={this.refHandlers.form}
              options={formOptions}
              type={formTypes}
              value={value}
            />
          </KeyboardAwareScrollView>
          <Button
            style={styles.button}
            onPress={this.save}
            isLoading={disabled}
            text={strings.SAVE}
            icon="md-checkmark"
          />
        </View>
      </ScrollView>
```
actually I've used `"react-native": "0.49.3"` and `"tcomb-form-native": "^0.6.9"`

**Comment by magigedaniel** [comment]
Was this issue "Tcomb form native handles keyboard behavior?" resolved in react native! Experiencng same issue?
