### ISSUE TITLE
Support for modal screens (two-page form edit)?

### ISSUE THREAD

**Issue by aksonov** [gcanti/tcomb-form-native#25]
Thanks for great component. The problem I can't figure out how to implement standard iOS two-screen approach for editing data, like first screen displays data with ">" arrows, after user clicks, user will could adjust that value. For example for gender it will display "Gender     Male >" on first screen, and UIPicker within modal on second. Or text area "About me            data  >" on first screen and UITextView with modal on second?

**Comment by irony** [comment]
+1

**Comment by carbureted** [comment]
+1

**Comment by GrumpyPants** [comment]
:+1:

**Comment by alvaromb** [comment]
Can you provide a visual example for that @aksonov ?

**Comment by alvaromb** [comment]
Also keep in mind that what you're trying to do involves some `Navigator` or `NavigatorIOS` around, and in my opinion that's not what this library tries to solve. You can easily create validated forms with `tcomb-form-native` and wrap 'em into whatever view hierarchy or flux you want, but I'm not sure this library should auto-generate a more complex view navigation.

Small libs to solve concrete problems is the way. If you want to auto-generate that form with navigation, you should create a library on top of `tcomb-form-native` in order to provide that functionality. Please ping me if you need help doing that, I'm open to collaborate :)

**Comment by GrumpyPants** [comment]
I can't speak for @aksonov but I personally imagine something like [this](https://raw.githubusercontent.com/FaridSafi/react-native-gifted-form/master/capture/signup.gif). The Gender and Country options open up a new 'modal' screen with the widget instead of it being on the same page. 

Maybe the view navigation would not be so complex though since it is really just pushing and then popping 1 scene? I am new to react native so maybe it would not be so easy. You make a good point @alvaromb and maybe this is outside of the goal of this lib. 

This is just my opinion but in tcomb-form for the web it makes sense for the form to be all on one page most of the time but for phone apps where modals are more common it would be nice if there was an **isModal** prop for each widget or something like that. For my use case I would be happy with just an example of how to integrate/recreate this interaction with tcomb-form-native.

**Comment by alvaromb** [comment]
You actually **can** do that, @GrumpyPants, the only thing is that `tcomb-form-native` doesn't provide those templates for you. I have done this by myself in two apps without any problem. You need a `Navigator` in order to make that transition, and my point is that this library shouldn't enforce you to use it. Don't get me wrong, `react-native-gifted-form` is very cool, but I think that the goal of this library is another one.

If you look closely to the gif you posted, the modal transition is wrong, because the navigation bar simulates a push-like transition when the contained view in the modal is opening bottom-to-top, not left-to-right.

Anyway, we could try to offer different templates with similar behaviour, but keep in mind that offering great templates with good customization involves a lot of things in this case: `NavigationBar`, `Button`'s for the navbar, transition, the touchable component that triggers the modal opening...

**Comment by bchoddny** [comment]
+1

**Comment by alvaromb** [comment]
How do you feel about this @gcanti? Maybe we could stick something into the docs, but it is out of the scope of this library IMHO.

**Comment by gcanti** [comment]
> but it is out of the scope of this library IMHO

I agree, going to close this.
