### ISSUE TITLE
Is it possible to target a single formgroup in one form?

### ISSUE THREAD

**Issue by brookehurford** [gcanti/tcomb-form-native#320]
Not sure the best way to just ask a question, but I'm trying to make my boolean select fields use flexDirection: 'row', without all my text fields using text row.

Appreciate any help someone can give me!

**Comment by hisshash** [comment]
I've been trying something similar. This is where I got to;

```

  componentDidMount = () => {
    this.refs.form.getComponent('name').refs.input.setNativeProps({width: width/2});
  }

```

I'm trying to target the actual input and change the width that way. IDK why but this effects all the inputs & I'm not sure if this is even a good way to do it.

I think you may need to look into [templating](https://github.com/gcanti/tcomb-form-native#templates) perhaps. 

Let me know if you figure anything out!

**Comment by alvaromb** [comment]
Hi @brookehurford!

I would go with the template path. It allows you to customise the templates of your fields and it won't affect any other field. There are some templates you can find in the issues and also you can read the actual templates of the library: https://github.com/gcanti/tcomb-form-native/tree/master/lib/templates/bootstrap

If you need to implement custom behaviour, you may consider to use a factory instead of a template. Here you have a complete example: https://github.com/APSL/react-native-floating-label

Please feel free to ping me if you need further assistance and I'll reopen the issue.
