### ISSUE TITLE
is there a way to externally validate without ref?

### ISSUE THREAD

**Issue by lifeiscontent** [gcanti/tcomb-form-native#439]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.11
- react-native v0.50.3

### Expected behaviour

Tell us what should happen

tcomb-form-native seems to not be able to set `hasError` without a ref.

since state, redux, or any other state container know the entire state of the form, it can call t.validate() on it to check if the state is indeed valid, there for, knowing that the UI is in a bad state.

### Actual behaviour

seems there's no way to pass `hasError` to `<Form />`

### Steps to reproduce

N/A

**Comment by ltankey** [comment]
Best way I found was to call `validate` on update, and to pass this along to your redux state. So rather than your redux state telling the component there's an error, let it manage its internal state and provide (as part of its form change update) redux with the form data, as well as there are any validation errors.

I did try to use the underlying validator functions with the form data and schema, but that didn't seem to work and this was the most direct path.
