### ISSUE TITLE
Support request:  How to set default values in an ES6 component?

### ISSUE THREAD

**Issue by arnoldbird** [gcanti/tcomb-form-native#463]
The README provides ES5 examples.  My experiments with ES6 are not working...

```
constructor(props) {
    super(props);
    this.state = {
      value: {
        name: 'Giulio',
        surname: 'Canti'
      }
    };
 }
```

Flow is giving me an error I don't understand:  "[flow] Cannot assign object literal to `this.state` because object literal [1] is incompatible with undefined [2]. (References: [1] [2])"

**Comment by Dreyer** [comment]
Because you're using Flow, you probably need to declare a `type` for `this.state`:

See docs on adding state:
https://flow.org/en/docs/react/components/#toc-adding-state

Further SO answers here too:
https://stackoverflow.com/questions/36860349/flow-react-native-is-giving-me-errors-for-using-this-state

**Comment by alvaromb** [comment]
This is a Flow question, please try to get support from Flowtype or StackOverflow.
