### ISSUE TITLE
The word "undefined" shows up wherever I use the <Form /> tag

### ISSUE THREAD

**Issue by ameshkin** [gcanti/tcomb-form-native#533]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.17

### Issue

The word undefined shows up wherever I put this form tag.

#### My code is here

```
    <View>

        <Form
          ref="form"
          type={ Person }
          options={ options }
        />

        <Button block
              style={formStyles.submitButton}
              onPress={this.handleSubmit}
              >
          <Text style={formStyles.submitButtonText}>
            SIGN UP
          </Text>
        </Button>
      </View>
```

**Comment by smerkousdavid** [comment]
I'm not entirely sure what the options you provided are but the latest commit broke all of my forms by adding the undefined to my labels because the else statement that's supposed to handle i18n optional / required fields breaks the label by adding an undefined if you don't include it in your options. I don't include an optional and required field in my labels so that was kind of annoying, but here is a temporary fix that I've got working.

```
const formOptions = {
  fields: {
     firstInput: {
       label: 'My label',
       placeholder: 'Required',
       i18n: {
         optional: '',
         required: ''
       }
     }
  }
};

const formType = tf.struct({
    firstInput: tf.String
});

...

<Form
  ref={ref => this.form = ref}
  type={formType}
  options={formOptions}
/>

...
```

**Comment by tonycoco** [comment]
#531 fixes this

**Comment by alvaromb** [comment]
https://github.com/gcanti/tcomb-form-native/releases/tag/v0.6.18
