### ISSUE TITLE
Is it possible to create a custom select option?

### ISSUE THREAD

**Issue by davidsims9t** [gcanti/tcomb-form-native#59]
Is it possible to replace PickerIOS with a custom select option if I'm using a custom template? Basically what I'm looking to do is create a button to navigate to another screen, allow a user to select an option, then update the picker with the option. I think I could get it to work if I can pass properties on to the specific field I'm editing and then modify the value of the field after the value has been selected from the other screen.

**Comment by hrlarsen** [comment]
I created almost this. In my case I wanted to be able to dynamically add new items to a picker, and when returning, select the newly added item. In my case I am using NavigatorIOS, and when navigating to the new site (from an "Add" button) I simply make sure that I have a callback set for it. When navigating to the new site I make sure that the current state is saved (for restoring the state upon return)

`````javascript
// make sure that state is saved past this point, though if keeping it up to date in onChange it shouldn't be a problem. 
this.props.navigator.push({
	leftButtonTitle: 'Cancel',
	onLeftButtonPress: () => this.props.navigator.pop(),
	title: 'Register Item',
	component: RegisterItem,
        callback: this.onReturnFromAdd
});
`````

upon return I then make sure that I call the callback so that the previous window knows what value have just been added/selected.

`````javascript
this.props.route.callback(Item);
this.props.navigator.pop();
``````

back in the list with the PickerIOS I simply set the state of the newly returned item

`````javascript
onReturnFromAdd(item)
{
  this.setState({value: item});
}
``````
And of course your picker form should have value pointing to the state value

``````javascript
<Form
ref="form"
type={Models.Location()}
value={this.state.value}
onChange={this.onChange}/>
`````

Hope this helps you find a solution :)

**Comment by alvaromb** [comment]
I'm very interested in bringing this feature into ``tcomb-form-native`` but I highly doubt that the best way to handle it is to make use of navigators. You should be able to tap into the option field and then let the handling of the selection to the user. Once the user has selected the option value, then the library should expose some way to set the value and display it near the option field.

We cannot force the user to use ``Navigator`` or ``NavigatorIOS``, but we should provide a component for the select options that can handle the option selection outside tcomb. It should not replace the default select, it should be another component. I would like to bring @gcanti into the discussion, because this is a feature that I need to implement for one of our apps and I would be more than happy to provide a PR.

Last but not least, the default ``Select`` component should have an option for displaying the picker outside it's view. Something like ![this](https://cloud.githubusercontent.com/assets/289640/10846847/eb129ef4-7f12-11e5-858b-018e62034e8f.png) but built for both platforms, iOS and Android. Maybe it could be done using react-native's ``<Modal />`` component and displaying the picker inside it.

**Comment by machard** [comment]
i have something similar:

```
// BottomModalDate

class StandaloneModal extends PureComponent {
  static propTypes = {
    children: React.PropTypes.node
  }

  state = {
    visible: false
  }

  setVisible(visible) {
    this.setState({visible});
  }

  render() {
    return (<Modal
      animated
      ref="modal"
      transparent
      visible={this.state.visible}
    >
      {this.props.children}
    </Modal>);
  }
}

export class BottomModalDate extends t.form.DatePicker {

  getTemplate() {
    // need to do this intermediate StandaloneModal component
    // because the function is not reexecuted when updating
    // state
    return (locals) => {
      return (<View>
        <Button
          label={locals.label + ' - ' + locals.value}
          onPress={() => {
            this.refs.modal.setVisible(true);
          }}
        />
        <StandaloneModal ref="modal">
          <View style={style.modal}>
            <View style={style.modalInner}>
              <View style={style.modalHeader}>
                <View style={style.dummy} />
                <Button
                  label={"OK"}
                  onPress={() => this.refs.modal.setVisible(false)}
                />
              </View>
              {t.form.Form.templates.datepicker({...locals, label: null})}
            </View>
          </View>
        </StandaloneModal>
      </View>);
    };
  }
};

```

**Comment by alvaromb** [comment]
I have a working example @davidsims9t, let me know if you want a gist and I'll create one with a simple example.

**Comment by jfsemaan** [comment]
Hi @alvaromb, do you have a working example for displaying the date picker outside it's view, like the example you posted?

Thanks.

**Comment by alvaromb** [comment]
I have an outside view with an autocomplete and a collapsible date picker component. Let me know which one would you like me to show you.

**Comment by jfsemaan** [comment]
@alvaromb thanks for your help. Could you post both examples? It would be nice to have different alternatives.

**Comment by alvaromb** [comment]
Here you have an ``AccordionPicker`` component @jfsemaan :

```es6
import React, { View, Text } from 'react-native'
import t from 'tcomb-form-native'
import Accordion from 'react-native-collapsible/Accordion'

const Select = t.form.Select

class AccordionPicker extends Select {
  _renderHeader (locals) {
    const valueText = locals.options.find(element => {
      return element.value === locals.value
    })
    let controlLabelStyle = locals.stylesheet.controlLabel.normal
    if (locals.hasError) {
      controlLabelStyle = locals.stylesheet.controlLabel.error
    }
    return (
      <View style={[styles.header, styles.textContainer]}>
        <Text style={[styles.label, controlLabelStyle]}>
          {locals.label}
        </Text>
        <Text style={[locals.stylesheet.controlLabel.normal, styles.value]}>
          {valueText.text}
        </Text>
      </View>
    )
  }

  _renderContent (locals) {
    return (
      <View>
        {t.form.Form.templates.select({...locals, label: null})}
      </View>
    )
  }

  getTemplate () {
    var self = this
    return function (locals) {
      return (
        <Accordion
          style={styles.container}
          sections={['Select']}
          renderHeader={self._renderHeader.bind(self, locals)}
          renderContent={self._renderContent.bind(self, locals)}
        />
      )
    }
  }
}

const styles = React.StyleSheet.create({
  container: {
    flex: 1,
    marginBottom: 10,
    backgroundColor: '#f9f9f9',
  },
  textContainer: {
    flexDirection: 'row',
    paddingLeft: 5,
    paddingRight: 5,
  },
  label: {
    fontSize: 16,
    alignSelf: 'center'
  },
  value: {
    flex: 1,
    fontSize: 16,
    textAlign: 'right',
    alignSelf: 'center',
    color: '#666'
  },
  header: {
    flex: 1,
    height: 44,
    backgroundColor: '#f9f9f9',
  },
})

export default AccordionPicker
```

**Comment by SudoPlz** [comment]
@alvaromb Could you please also post the  outside view example as well? I need to figure out a way to combine those two and get "exactly" the image you posted above..!

**Comment by sirwoetang** [comment]
@alvaromb the outside view example would be invaluable! Thanks for your help on this!

**Comment by SudoPlz** [comment]
I managed to create a collapsible datepicker, this is the way I did it in case someone is looking for it in the future: https://github.com/gcanti/tcomb-form-native/issues/61#issuecomment-204368116

**Comment by alvaromb** [comment]
I'm doing some optimizations to the outside view today, so please be patient. The current code isn't very good so I prefer to share something more solid.

**Comment by pseudorandumb** [comment]
@alvaromb do you have that example of using a separate view with navigator? Would be much appreciated, I'm trying to do the same and it's starting to get real hacky.

**Comment by kcfgl** [comment]
@alvaromb Do you happen to have that autocomplete example handy? I'm trying to do a super simple State autocomplete/autosuggest and it would be awesome to see if I'm on the right track. Thanks!
