### ISSUE TITLE
New floating-label factory

### ISSUE THREAD

**Issue by alvaromb** [gcanti/tcomb-form-native#89]
I've just created a factory to use with this library that provides floating label style inputs https://github.com/APSL/react-native-floating-label.

I would like to make ``tcomb-form-native`` easily extendable with custom factories. What's your opinion on that @gcanti? Should we keep this factories as separated repos or should we have a bunch of them inside the library?

**Comment by gcanti** [comment]
Factories are pretty customised. With the next version of tcomb-form I'm leaning towards external repos (also for the templates) in order to better manage **versions and patches**. Maybe it's a good strategy for tcomb-form-native as well. Also, we could add a section "Factories" in the README and link to the separated repos.

**Comment by alvaromb** [comment]
We should stick something in the docs. I can do that on Monday. Thoughts, @gcanti?

**Comment by alvaromb** [comment]
Docs are pretty good right now, closing this.
